export type ScoreValue = '1' | '0' | 'NA' | 'M' | null;

export interface IpdAuditTableRow {
  id: string;
  no: number;
  contentName: string;
  isSubRow?: boolean;
  naSelected?: boolean;
  missingSelected?: boolean;
  noSelected?: boolean; // กากบาทช่อง No (มีเอกสารแต่ไม่มีการบันทึก) ตามคู่มือ สปสช. หน้า 55, 68
  scores: ScoreValue[]; // เกณฑ์ข้อ 1 - 9 (หมวด 2 มี 7 เกณฑ์)
  maxCriteria: number; // 9 หรือ 7 ตามคู่มือ
  addScore: number;
  deductScore: number;
  remarkText?: string;
  canNA: boolean; // มีสิทธิ์เลือก NA หรือไม่ (ลำดับที่ 7, 8, 9, 10, 11 ตามคู่มือ สปสช.)
  hasAddScore?: boolean;
  hasDeductScore?: boolean; // หมวด 12 Nurses' note มีหัก 1 คะแนน
}

export const initialIpdAuditTableRows: IpdAuditTableRow[] = [
  {
    id: 'ipd_c1',
    no: 1,
    contentName: 'Discharge summary: Diagnosis, Operation',
    scores: [null, null, null, null, null, null, null, null, null],
    maxCriteria: 9,
    addScore: 0,
    deductScore: 0,
    remarkText: '',
    canNA: false,
    hasAddScore: false,
    hasDeductScore: false,
  },
  {
    id: 'ipd_c2',
    no: 2,
    contentName: 'Discharge summary: Others',
    scores: [null, null, null, null, null, null, null],
    maxCriteria: 7,
    addScore: 0,
    deductScore: 0,
    remarkText: '',
    canNA: false,
    hasAddScore: false,
    hasDeductScore: false,
  },
  {
    id: 'ipd_c3',
    no: 3,
    contentName: 'Informed consent',
    scores: [null, null, null, null, null, null, null, null, null],
    maxCriteria: 9,
    addScore: 0,
    deductScore: 0,
    remarkText: '',
    canNA: false,
    hasAddScore: false,
    hasDeductScore: false,
  },
  {
    id: 'ipd_c4',
    no: 4,
    contentName: 'History (บันทึกการซักประวัติโดยแพทย์)',
    scores: [null, null, null, null, null, null, null, null, null],
    maxCriteria: 9,
    addScore: 0,
    deductScore: 0,
    remarkText: '',
    canNA: false,
    hasAddScore: false,
    hasDeductScore: false,
  },
  {
    id: 'ipd_c5',
    no: 5,
    contentName: 'Physical exam (บันทึกการตรวจร่างกายโดยแพทย์)',
    scores: [null, null, null, null, null, null, null, null, null],
    maxCriteria: 9,
    addScore: 0,
    deductScore: 0,
    remarkText: '',
    canNA: false,
    hasAddScore: false,
    hasDeductScore: false,
  },
  {
    id: 'ipd_c6',
    no: 6,
    contentName: "Progress note และ Doctor's order sheet",
    scores: [null, null, null, null, null, null, null, null, null],
    maxCriteria: 9,
    addScore: 0,
    deductScore: 0,
    remarkText: '',
    canNA: false,
    hasAddScore: false,
    hasDeductScore: false,
  },
  {
    id: 'ipd_c7',
    no: 7,
    contentName: 'Consultation record (บันทึกการปรึกษา)',
    scores: [null, null, null, null, null, null, null, null, null],
    maxCriteria: 9,
    addScore: 0,
    deductScore: 0,
    remarkText: '',
    canNA: true,
    hasAddScore: false,
    hasDeductScore: false,
  },
  {
    id: 'ipd_c8',
    no: 8,
    contentName: 'Anesthetic record (บันทึกทางวิสัญญีวิทยา)',
    scores: [null, null, null, null, null, null, null, null, null],
    maxCriteria: 9,
    addScore: 0,
    deductScore: 0,
    remarkText: '',
    canNA: true,
    hasAddScore: false,
    hasDeductScore: false,
  },
  {
    id: 'ipd_c9',
    no: 9,
    contentName: 'Operative note (บันทึกการผ่าตัดหรือหัตถการ)',
    scores: [null, null, null, null, null, null, null, null, null],
    maxCriteria: 9,
    addScore: 0,
    deductScore: 0,
    remarkText: '',
    canNA: true,
    hasAddScore: false,
    hasDeductScore: false,
  },
  {
    id: 'ipd_c10',
    no: 10,
    contentName: 'Labour record (บันทึกการคลอด)',
    scores: [null, null, null, null, null, null, null, null, null],
    maxCriteria: 9,
    addScore: 0,
    deductScore: 0,
    remarkText: '',
    canNA: true,
    hasAddScore: false,
    hasDeductScore: false,
  },
  {
    id: 'ipd_c11',
    no: 11,
    contentName: 'Rehabilitation record (บันทึกการฟื้นฟูสมรรถภาพ)',
    scores: [null, null, null, null, null, null, null, null, null],
    maxCriteria: 9,
    addScore: 0,
    deductScore: 0,
    remarkText: '',
    canNA: true,
    hasAddScore: false,
    hasDeductScore: false,
  },
  {
    id: 'ipd_c12',
    no: 12,
    contentName: "Nurses' note (บันทึกการพยาบาล)",
    scores: [null, null, null, null, null, null, null, null, null],
    maxCriteria: 9,
    addScore: 0,
    deductScore: 0,
    remarkText: '',
    canNA: false,
    hasAddScore: false,
    hasDeductScore: true, // หัก 1 คะแนน กรณีบันทึกไม่ต่อเนื่องทุกวันทุกเวร
  },
];

export interface IpdCriteriaItem {
  id: string;
  rowId: string;
  criteriaIndex: number;
  category: string;
  criteriaNo: number;
  title: string;
  description: string;
  canBeNA: boolean;
}

export const allIpdCriteriaList: IpdCriteriaItem[] = [
  // ── 1. Discharge Summary: Diagnosis, Operation (9 ข้อ) ──
  {
    id: 'ipd_c1_1',
    rowId: 'ipd_c1',
    criteriaIndex: 0,
    category: '1. Discharge summary: Diagnosis, Operation',
    criteriaNo: 1,
    title: 'Principal Diagnosis (การวินิจฉัยโรคหลัก)',
    description: 'สรุปเป็น Clinical term ไม่สรุปเป็นรหัส ICD-10 สอดคล้องกับข้อมูลในเวชระเบียน และมีเพียงโรคเดียว',
    canBeNA: false,
  },
  {
    id: 'ipd_c1_2',
    rowId: 'ipd_c1',
    criteriaIndex: 1,
    category: '1. Discharge summary: Diagnosis, Operation',
    criteriaNo: 2,
    title: 'Comorbidity, Complication และ External Cause',
    description: 'สรุปโรคร่วมและโรคแทรกเป็น Clinical term สอดคล้องกับเวชระเบียน และสรุปสาเหตุการบาดเจ็บ/พิษ (ภาษาไทยได้เฉพาะ external cause ถ้าไม่มีระบุ NA)',
    canBeNA: true,
  },
  {
    id: 'ipd_c1_3',
    rowId: 'ipd_c1',
    criteriaIndex: 2,
    category: '1. Discharge summary: Diagnosis, Operation',
    criteriaNo: 3,
    title: 'สรุปการทำหัตถการและหรือการผ่าตัด (Procedure/Operation)',
    description: 'สรุปการทำหัตถการและหรือการผ่าตัดถูกต้องและครบถ้วนตรงกับข้อมูลในเวชระเบียน (ถ้าไม่มีระบุ NA)',
    canBeNA: true,
  },
  {
    id: 'ipd_c1_4',
    rowId: 'ipd_c1',
    criteriaIndex: 3,
    category: '1. Discharge summary: Diagnosis, Operation',
    criteriaNo: 4,
    title: 'บันทึกวันเดือนปีและเวลาผ่าตัดในห้องผ่าตัด (OR Procedure)',
    description: 'บันทึกวันเดือนปี และเวลาที่เริ่มต้นและสิ้นสุดของการทำหัตถการในห้องผ่าตัดทุกครั้ง (ถ้าไม่มีระบุ NA)',
    canBeNA: true,
  },
  {
    id: 'ipd_c1_5',
    rowId: 'ipd_c1',
    criteriaIndex: 4,
    category: '1. Discharge summary: Diagnosis, Operation',
    criteriaNo: 5,
    title: 'ไม่ใช้ตัวย่อที่ไม่เป็นมาตรฐานในการสรุปโรคและหัตถการ',
    description: 'ไม่ใช้ตัวย่อในการสรุป Principal dx, Comorbidity, Complication, External cause, Operation และสรุปด้วยลายมือที่อ่านออกได้',
    canBeNA: false,
  },
  {
    id: 'ipd_c1_6',
    rowId: 'ipd_c1',
    criteriaIndex: 5,
    category: '1. Discharge summary: Diagnosis, Operation',
    criteriaNo: 6,
    title: 'Clinical Summary ครบถ้วนโดยสังเขป',
    description: 'สรุปปัญหาแรกรับ/สิ้นสุด, investigated สำคัญ, การรักษาและผลที่จำเป็น, แผนฟื้นฟูหลังจำหน่าย และ Home medication',
    canBeNA: false,
  },
  {
    id: 'ipd_c1_7',
    rowId: 'ipd_c1',
    criteriaIndex: 6,
    category: '1. Discharge summary: Diagnosis, Operation',
    criteriaNo: 7,
    title: 'สรุปสาเหตุการตายสอดคล้องกับเวชระเบียน',
    description: 'สรุปสาเหตุการตายให้สอดคล้องกับข้อมูลในเวชระเบียน (กรณีผู้ป่วยไม่เสียชีวิตให้ระบุ NA)',
    canBeNA: true,
  },
  {
    id: 'ipd_c1_8',
    rowId: 'ipd_c1',
    criteriaIndex: 7,
    category: '1. Discharge summary: Diagnosis, Operation',
    criteriaNo: 8,
    title: 'Discharge Status และ Discharge Type ถูกต้อง',
    description: 'สรุป Discharge status และ Discharge type ถูกต้องตรงกับเวชระเบียน กรณี by transfer ต้องระบุชื่อสถานพยาบาลที่ส่งต่อ',
    canBeNA: false,
  },
  {
    id: 'ipd_c1_9',
    rowId: 'ipd_c1',
    criteriaIndex: 8,
    category: '1. Discharge summary: Diagnosis, Operation',
    criteriaNo: 9,
    title: 'ลายมือชื่อแพทย์ผู้รักษา/แพทย์ผู้สรุป และเลขที่ ว.',
    description: 'มีลายมือชื่อแพทย์ผู้ดูแลรักษา หรือแพทย์ผู้สรุป โดยระบุชื่อ นามสกุล และเลขที่ใบอนุญาตประกอบวิชาชีพเวชกรรม (หรือระบบ EMR ตรวจสอบได้)',
    canBeNA: false,
  },

  // ── 2. Discharge summary: Others (7 ข้อ) ──
  {
    id: 'ipd_c2_1',
    rowId: 'ipd_c2',
    criteriaIndex: 0,
    category: '2. Discharge summary: Others',
    criteriaNo: 1,
    title: 'ข้อมูลชื่อ-นามสกุล เพศ อายุ หรือวันเดือนปีเกิด',
    description: 'มีข้อมูลชื่อ นามสกุล เพศ อายุ หรือ วัน เดือน ปีเกิดของผู้ป่วย ถูกต้องครบถ้วน (ไม่ทราบวันเกิดอนุโลมให้มีปี พ.ศ.)',
    canBeNA: false,
  },
  {
    id: 'ipd_c2_2',
    rowId: 'ipd_c2',
    criteriaIndex: 1,
    category: '2. Discharge summary: Others',
    criteriaNo: 2,
    title: 'เลขประจำตัวประชาชน 13 หลัก หรือเลขที่ใบต่างด้าว',
    description: 'มีข้อมูลเลขประจำตัวประชาชน หรือเลขที่ใบต่างด้าว/พาสปอร์ต (ไม่รู้สึกตัว/เสียชีวิตไม่พบหลักฐานให้ระบุไว้)',
    canBeNA: false,
  },
  {
    id: 'ipd_c2_3',
    rowId: 'ipd_c2',
    criteriaIndex: 2,
    category: '2. Discharge summary: Others',
    criteriaNo: 3,
    title: 'ข้อมูลที่อยู่ปัจจุบันของผู้ป่วย',
    description: 'มีข้อมูลที่อยู่ปัจจุบันของผู้ป่วย (กรณีไม่รู้สึกตัว/ซักประวัติไม่ได้ ต้องระบุในเวชระเบียน)',
    canBeNA: false,
  },
  {
    id: 'ipd_c2_4',
    rowId: 'ipd_c2',
    criteriaIndex: 3,
    category: '2. Discharge summary: Others',
    criteriaNo: 4,
    title: 'ชื่อโรงพยาบาล HN และ AN ถูกต้องตรงกันทุกแห่ง',
    description: 'มีข้อมูลชื่อโรงพยาบาล HN และ AN ถูกต้องตรงกับข้อมูลที่ปรากฏทุกแห่งในเวชระเบียน',
    canBeNA: false,
  },
  {
    id: 'ipd_c2_5',
    rowId: 'ipd_c2',
    criteriaIndex: 4,
    category: '2. Discharge summary: Others',
    criteriaNo: 5,
    title: 'วันเดือนปีและเวลา Admit และ Discharge',
    description: 'มีข้อมูลวัน เดือน ปี และเวลาที่ admit และ discharge ถูกต้องตรงกับข้อมูลในเวชระเบียน',
    canBeNA: false,
  },
  {
    id: 'ipd_c2_6',
    rowId: 'ipd_c2',
    criteriaIndex: 5,
    category: '2. Discharge summary: Others',
    criteriaNo: 6,
    title: 'จำนวนวันนอน (LOS) และวันลากลับบ้าน (Leave days)',
    description: 'มีข้อมูลจำนวนวันที่อยู่ในโรงพยาบาล (LOS) และจำนวนวันที่ลากลับบ้าน (total leave days) ถูกต้องตรงกับเวชระเบียน',
    canBeNA: false,
  },
  {
    id: 'ipd_c2_7',
    rowId: 'ipd_c2',
    criteriaIndex: 6,
    category: '2. Discharge summary: Others',
    criteriaNo: 7,
    title: 'ข้อมูลชื่อ-นามสกุล ผู้ให้รหัสโรคและรหัสหัตถการ',
    description: 'มีข้อมูล ชื่อ นามสกุล ผู้ให้รหัสโรค และข้อมูลชื่อ นามสกุล ผู้ให้รหัสหัตถการครบถ้วน',
    canBeNA: false,
  },

  // ── 3. Informed consent (9 ข้อ) ──
  {
    id: 'ipd_c3_1',
    rowId: 'ipd_c3',
    criteriaIndex: 0,
    category: '3. Informed consent',
    criteriaNo: 1,
    title: 'ชื่อและนามสกุลผู้ป่วยถูกต้องชัดเจน',
    description: 'มีการบันทึกชื่อ และนามสกุล ผู้ป่วยถูกต้องชัดเจนในใบยินยอม',
    canBeNA: false,
  },
  {
    id: 'ipd_c3_2',
    rowId: 'ipd_c3',
    criteriaIndex: 1,
    category: '3. Informed consent',
    criteriaNo: 2,
    title: 'ลายมือชื่อผู้ให้คำอธิบาย (ชื่อ สกุล ตำแหน่ง)',
    description: 'มีลายมือชื่อผู้ให้คำอธิบาย (ระบุชื่อ นามสกุล และตำแหน่ง) เกี่ยวกับการรักษาก่อนการลงนามยินยอมหรือปฏิเสธ',
    canBeNA: false,
  },
  {
    id: 'ipd_c3_3',
    rowId: 'ipd_c3',
    criteriaIndex: 2,
    category: '3. Informed consent',
    criteriaNo: 3,
    title: 'ลายมือชื่อ/พิมพ์นิ้วมือ ชื่อและนามสกุลผู้รับทราบข้อมูลและยินยอม',
    description: 'มีลายมือชื่อหรือลายพิมพ์นิ้วมือ ชื่อ นามสกุล ผู้ยินยอม (กรณี <18 ปี หรือไม่สมบูรณ์ มีผู้ยินยอมแทน ยกเว้นภาวะฉุกเฉิน)',
    canBeNA: false,
  },
  {
    id: 'ipd_c3_4',
    rowId: 'ipd_c3',
    criteriaIndex: 3,
    category: '3. Informed consent',
    criteriaNo: 4,
    title: 'ลายมือชื่อพยานฝ่ายผู้ป่วยและระบุความสัมพันธ์',
    description: 'มีลายมือชื่อหรือลายพิมพ์นิ้วมือของพยานฝ่ายผู้ป่วย 1 คน ระบุชื่อ สกุล และความสัมพันธ์ (กรณีมาคนเดียว ระบุ "มาคนเดียว")',
    canBeNA: false,
  },
  {
    id: 'ipd_c3_5',
    rowId: 'ipd_c3',
    criteriaIndex: 4,
    category: '3. Informed consent',
    criteriaNo: 5,
    title: 'ลายมือชื่อพยานฝ่ายเจ้าหน้าที่โรงพยาบาล',
    description: 'มีลายมือชื่อพยานฝ่ายเจ้าหน้าที่โรงพยาบาล 1 คน ระบุชื่อ นามสกุล ตำแหน่ง โดยต้องไม่เป็นบุคคลเดียวกับผู้ให้คำอธิบาย',
    canBeNA: false,
  },
  {
    id: 'ipd_c3_6',
    rowId: 'ipd_c3',
    criteriaIndex: 5,
    category: '3. Informed consent',
    criteriaNo: 6,
    title: 'รายละเอียดเหตุผล ความจำเป็น และวิธีการรักษา/หัตถการ',
    description: 'มีข้อมูลรายละเอียดเหตุผล ความจำเป็นในการรักษา วิธีการรักษาหรือหัตถการ การใช้ยาระงับความรู้สึก สอดคล้องกับปัญหา',
    canBeNA: false,
  },
  {
    id: 'ipd_c3_7',
    rowId: 'ipd_c3',
    criteriaIndex: 6,
    category: '3. Informed consent',
    criteriaNo: 7,
    title: 'ข้อมูลทางเลือก ข้อดี และข้อเสียของทางเลือก',
    description: 'มีข้อมูลรายละเอียดเกี่ยวกับทางเลือก ข้อดี ข้อเสียของทางเลือกในการรักษาที่แจ้งแก่ผู้ป่วยและญาติรับทราบ',
    canBeNA: false,
  },
  {
    id: 'ipd_c3_8',
    rowId: 'ipd_c3',
    criteriaIndex: 7,
    category: '3. Informed consent',
    criteriaNo: 8,
    title: 'ระยะเวลา ผลการรักษา ความเสี่ยง และภาวะแทรกซ้อน',
    description: 'มีข้อมูลรายละเอียดเกี่ยวกับระยะเวลาในการรักษา ผลการรักษา ความเสี่ยง และภาวะแทรกซ้อนที่อาจเกิดขึ้น',
    canBeNA: false,
  },
  {
    id: 'ipd_c3_9',
    rowId: 'ipd_c3',
    criteriaIndex: 8,
    category: '3. Informed consent',
    criteriaNo: 9,
    title: 'วันเดือนปีและเวลาที่รับทราบและยินยอม',
    description: 'มีการบันทึกระบุ วัน เดือน ปี และเวลา ที่รับทราบและยินยอมให้ทำการรักษาอย่างชัดเจน',
    canBeNA: false,
  },

  // ── 4. History (9 ข้อ) ──
  {
    id: 'ipd_c4_1',
    rowId: 'ipd_c4',
    criteriaIndex: 0,
    category: '4. History (บันทึกการซักประวัติโดยแพทย์)',
    criteriaNo: 1,
    title: 'Chief Complaint (อาการสำคัญและระยะเวลา)',
    description: 'บันทึก chief complaint: อาการและระยะเวลา หรือปัญหาที่ผู้ป่วยต้องมารักษาที่โรงพยาบาล',
    canBeNA: false,
  },
  {
    id: 'ipd_c4_2',
    rowId: 'ipd_c4',
    criteriaIndex: 1,
    category: '4. History (บันทึกการซักประวัติโดยแพทย์)',
    criteriaNo: 2,
    title: 'Present Illness ในส่วน 5W, 2H อย่างน้อย 3 ข้อ',
    description: 'บันทึก 5W, 2H (what, where, when, why, who, how, how many) อย่างน้อย 3 ข้อ (ไม่รู้สึกตัว/ซักไม่ได้ระบุในชาร์ต)',
    canBeNA: false,
  },
  {
    id: 'ipd_c4_3',
    rowId: 'ipd_c4',
    criteriaIndex: 2,
    category: '4. History (บันทึกการซักประวัติโดยแพทย์)',
    criteriaNo: 3,
    title: 'การรักษาที่ได้รับมาก่อนหน้า หรือประวัติการรักษาที่ผ่านมา',
    description: 'บันทึกการรักษาที่ได้มาแล้ว รวมถึงการกินยาเองจากบ้าน (ถ้าไม่เคยรักษาที่ใดระบุ "ไม่ได้รักษาจากที่ใด")',
    canBeNA: false,
  },
  {
    id: 'ipd_c4_4',
    rowId: 'ipd_c4',
    criteriaIndex: 3,
    category: '4. History (บันทึกการซักประวัติโดยแพทย์)',
    criteriaNo: 4,
    title: 'Past Illness ที่สำคัญและเกี่ยวข้องกับปัญหาที่มา',
    description: 'บันทึกประวัติเจ็บป่วยในอดีตที่สำคัญ หรือสอดคล้องกับปัญหาที่สงสัย (ถ้าไม่มีระบุว่าไม่มี)',
    canBeNA: false,
  },
  {
    id: 'ipd_c4_5',
    rowId: 'ipd_c4',
    criteriaIndex: 4,
    category: '4. History (บันทึกการซักประวัติโดยแพทย์)',
    criteriaNo: 5,
    title: 'ประวัติการแพ้ยาและแพ้อื่นๆ พร้อมระบุชื่อสิ่งที่แพ้',
    description: 'บันทึกประวัติแพ้ยาและแพ้อื่นๆ พร้อมระบุชื่อยา/สิ่งที่แพ้ (ถ้าไม่มีระบุ "ไม่มีประวัติแพ้ยาและการแพ้อื่นๆ")',
    canBeNA: false,
  },
  {
    id: 'ipd_c4_6',
    rowId: 'ipd_c4',
    criteriaIndex: 5,
    category: '4. History (บันทึกการซักประวัติโดยแพทย์)',
    criteriaNo: 6,
    title: 'ประวัติอื่นๆ (Family/Personal/Social/ประจำเดือน/วัคซีน)',
    description: 'บันทึก Family/Personal/Social/ประวัติทำงาน, หญิง 11-60 ปีบันทึกประจำเดือน, เด็ก 0-14 ปีบันทึกวัคซีนและพัฒนาการ',
    canBeNA: false,
  },
  {
    id: 'ipd_c4_7',
    rowId: 'ipd_c4',
    criteriaIndex: 6,
    category: '4. History (บันทึกการซักประวัติโดยแพทย์)',
    criteriaNo: 7,
    title: 'Review of Systems ทุกระบบ',
    description: 'บันทึกการซักประวัติการเจ็บป่วยของระบบร่างกายอื่นๆ (review of system) ครบทุกระบบ',
    canBeNA: false,
  },
  {
    id: 'ipd_c4_8',
    rowId: 'ipd_c4',
    criteriaIndex: 7,
    category: '4. History (บันทึกการซักประวัติโดยแพทย์)',
    criteriaNo: 8,
    title: 'ลายมือชื่อแพทย์ผู้ซักประวัติ และเลขที่ ว.',
    description: 'บันทึกด้วยลายมือชื่อแพทย์ ระบุชื่อ นามสกุล และเลขที่ใบอนุญาตประกอบวิชาชีพเวชกรรม (ว.) หรือระบบคอมพิวเตอร์สืบค้นได้',
    canBeNA: false,
  },
  {
    id: 'ipd_c4_9',
    rowId: 'ipd_c4',
    criteriaIndex: 8,
    category: '4. History (บันทึกการซักประวัติโดยแพทย์)',
    criteriaNo: 9,
    title: 'ระบุแหล่งที่มาของข้อมูล (Source of history)',
    description: 'ระบุแหล่งที่มาของข้อมูล เช่น ได้จากตัวผู้ป่วยเอง ญาติ ประวัติเก่าในเวชระเบียน หรือใบส่งต่อ (refer)',
    canBeNA: false,
  },

  // ── 5. Physical Examination (9 ข้อ) ──
  {
    id: 'ipd_c5_1',
    rowId: 'ipd_c5',
    criteriaIndex: 0,
    category: '5. Physical exam (บันทึกการตรวจร่างกายโดยแพทย์)',
    criteriaNo: 1,
    title: 'Vital signs แรกรับ (T, PR, RR, BP)',
    description: 'บันทึก Vital signs: temperature, pulse rate, respiration rate และ blood pressure (BP ยกเว้นเด็ก < 5 ปี)',
    canBeNA: false,
  },
  {
    id: 'ipd_c5_2',
    rowId: 'ipd_c5',
    criteriaIndex: 1,
    category: '5. Physical exam (บันทึกการตรวจร่างกายโดยแพทย์)',
    criteriaNo: 2,
    title: 'บันทึกน้ำหนักทุกราย และส่วนสูงตามเกณฑ์',
    description: 'มีบันทึกน้ำหนักทุกราย และส่วนสูงในเด็กทุกราย หรือผู้ใหญ่ที่ต้องใช้ค่า BMI/BSA (ชั่งไม่ได้ต้องระบุเหตุผล)',
    canBeNA: false,
  },
  {
    id: 'ipd_c5_3',
    rowId: 'ipd_c5',
    criteriaIndex: 2,
    category: '5. Physical exam (บันทึกการตรวจร่างกายโดยแพทย์)',
    criteriaNo: 3,
    title: 'ตรวจร่างกาย ดู คลำ เคาะ ฟัง ที่สอดคล้องกับ CC',
    description: 'บันทึกตรวจร่างกาย ดู คลำ เคาะ ฟัง สอดคล้องกับ CC ซึ่งมิใช่เขียนแค่คำว่า "ปกติ" หรือ "WNL"',
    canBeNA: false,
  },
  {
    id: 'ipd_c5_4',
    rowId: 'ipd_c5',
    criteriaIndex: 3,
    category: '5. Physical exam (บันทึกการตรวจร่างกายโดยแพทย์)',
    criteriaNo: 4,
    title: 'วาดรูปหรือแสดงกราฟิกสิ่งที่ตรวจพบความผิดปกติ',
    description: 'มีการบันทึกโดยการวาดรูปหรือแสดงกราฟิกสิ่งที่ผิดปกติ (กรณีตรวจไม่พบความผิดปกติ ให้ระบุ NA โดยต้องได้คะแนนในข้อ 3)',
    canBeNA: true,
  },
  {
    id: 'ipd_c5_5',
    rowId: 'ipd_c5',
    criteriaIndex: 4,
    category: '5. Physical exam (บันทึกการตรวจร่างกายโดยแพทย์)',
    criteriaNo: 5,
    title: 'บันทึกการตรวจร่างกายทุกระบบ',
    description: 'มีการบันทึกการตรวจร่างกายทุกระบบ มิใช่เขียนแค่คำว่า "ปกติ" หรือเขียนว่า "ทุกระบบ WNL"',
    canBeNA: false,
  },
  {
    id: 'ipd_c5_6',
    rowId: 'ipd_c5',
    criteriaIndex: 5,
    category: '5. Physical exam (บันทึกการตรวจร่างกายโดยแพทย์)',
    criteriaNo: 6,
    title: 'สรุปปัญหาของผู้ป่วยแรกรับ (Problem list)',
    description: 'มีการสรุปปัญหาของผู้ป่วยที่เข้ารับการรักษาในครั้งนี้ (problem list) ชัดเจน',
    canBeNA: false,
  },
  {
    id: 'ipd_c5_7',
    rowId: 'ipd_c5',
    criteriaIndex: 6,
    category: '5. Physical exam (บันทึกการตรวจร่างกายโดยแพทย์)',
    criteriaNo: 7,
    title: 'สรุปการวินิจฉัยขั้นต้น (Provisional diagnosis)',
    description: 'มีการสรุปวินิจฉัยขั้นต้นที่สอดคล้องกับประวัติและผลการตรวจร่างกาย',
    canBeNA: false,
  },
  {
    id: 'ipd_c5_8',
    rowId: 'ipd_c5',
    criteriaIndex: 7,
    category: '5. Physical exam (บันทึกการตรวจร่างกายโดยแพทย์)',
    criteriaNo: 8,
    title: 'รายละเอียดแผนการรักษาในการ Admit ครั้งนี้',
    description: 'บันทึกรายละเอียดแผนการรักษาในการ admit ครั้งนี้ (กรณีบันทึกแค่ว่า admit ถือว่าไม่ผ่านเกณฑ์)',
    canBeNA: false,
  },
  {
    id: 'ipd_c5_9',
    rowId: 'ipd_c5',
    criteriaIndex: 8,
    category: '5. Physical exam (บันทึกการตรวจร่างกายโดยแพทย์)',
    criteriaNo: 9,
    title: 'ลายมือชื่อแพทย์ผู้ตรวจร่างกาย และเลขที่ ว.',
    description: 'มีลายมือชื่อแพทย์ผู้รับผิดชอบตรวจร่างกาย ระบุชื่อ นามสกุล และเลขที่ใบอนุญาตประกอบวิชาชีพเวชกรรม',
    canBeNA: false,
  },

  // ── 6. Progress notes และ Doctor's order sheet (9 ข้อ) ──
  {
    id: 'ipd_c6_1',
    rowId: 'ipd_c6',
    criteriaIndex: 0,
    category: "6. Progress note และ doctor's order",
    criteriaNo: 1,
    title: 'ลงวันเดือนปีและเวลาทุกครั้งที่บันทึก Progress note',
    description: 'มีการลงวันเดือนปี และเวลา ทุกครั้งที่บันทึก progress note อย่างสม่ำเสมอ',
    canBeNA: false,
  },
  {
    id: 'ipd_c6_2',
    rowId: 'ipd_c6',
    criteriaIndex: 1,
    category: "6. Progress note และ doctor's order",
    criteriaNo: 2,
    title: 'บันทึกทุกวันใน 3 วันแรกของการ Admit',
    description: 'มีการบันทึก progress note ทุกวันใน 3 วันแรก (กรณีจิตเวช: อย่างน้อย 1 ครั้งใน 3 วันแรก และ 1 ครั้งต่อสัปดาห์)',
    canBeNA: false,
  },
  {
    id: 'ipd_c6_3',
    rowId: 'ipd_c6',
    criteriaIndex: 2,
    category: "6. Progress note และ doctor's order",
    criteriaNo: 3,
    title: 'บันทึกเนื้อหาครอบคลุม SOAP ใน 3 วันแรก',
    description: 'บันทึกเนื้อหาครอบคลุม SOAP (Subjective, Objective, Assessment, Plan) ใน 3 วันแรก',
    canBeNA: false,
  },
  {
    id: 'ipd_c6_4',
    rowId: 'ipd_c6',
    criteriaIndex: 3,
    category: "6. Progress note และ doctor's order",
    criteriaNo: 4,
    title: 'บันทึกทุกครั้งที่มีการเปลี่ยนแปลงอาการ/การรักษา/หัตถการ',
    description: 'บันทึกทุกครั้งที่มีการเปลี่ยนแปลงอาการ การรักษา การให้ยา การทำ invasive procedure หรือเปลี่ยนแพทย์ผู้ดูแล',
    canBeNA: false,
  },
  {
    id: 'ipd_c6_5',
    rowId: 'ipd_c6',
    criteriaIndex: 4,
    category: "6. Progress note และ doctor's order",
    criteriaNo: 5,
    title: 'บันทึกครอบคลุม SOAP ทุกครั้งที่มีการเปลี่ยนแปลง',
    description: 'บันทึกเนื้อหาครอบคลุม SOAP ทุกครั้งที่มีการเปลี่ยนแปลงอาการ การรักษา หรือทำหัตถการ',
    canBeNA: false,
  },
  {
    id: 'ipd_c6_6',
    rowId: 'ipd_c6',
    criteriaIndex: 5,
    category: "6. Progress note และ doctor's order",
    criteriaNo: 6,
    title: 'บันทึกแปลผล Investigation สำคัญและวางแผนการรักษา',
    description: 'บันทึกแปลผล investigation ที่สำคัญ และมีการวินิจฉัยร่วมกับการวางแผนรักษาเมื่อผลผิดปกติ',
    canBeNA: false,
  },
  {
    id: 'ipd_c6_7',
    rowId: 'ipd_c6',
    criteriaIndex: 6,
    category: "6. Progress note และ doctor's order",
    criteriaNo: 7,
    title: 'บันทึก Progress note ลงตรงตำแหน่งที่หน่วยบริการกำหนด',
    description: 'บันทึก progress note ลงตรงตำแหน่งหรือแบบฟอร์มที่โรงพยาบาลกำหนด',
    canBeNA: false,
  },
  {
    id: 'ipd_c6_8',
    rowId: 'ipd_c6',
    criteriaIndex: 7,
    category: "6. Progress note และ doctor's order",
    criteriaNo: 8,
    title: 'ลายมือชื่อแพทย์ผู้บันทึก Progress note ที่ระบุตัวตนได้',
    description: 'บันทึกด้วยลายมือที่อ่านออกได้ และลงลายมือชื่อแพทย์ผู้รับผิดชอบที่ระบุตัวตนได้ (หรือตรวจสอบ EMR login)',
    canBeNA: false,
  },
  {
    id: 'ipd_c6_9',
    rowId: 'ipd_c6',
    criteriaIndex: 8,
    category: "6. Progress note และ doctor's order",
    criteriaNo: 9,
    title: "ลง ว/ด/ป เวลา และลงนามใน Doctor's order sheet ทุกครั้ง",
    description: "ลงวันเดือนปี เวลา และลงนามกำกับในใบคำสั่งการรักษา doctor's order (ทั้ง one day และ continue) ทุกครั้ง",
    canBeNA: false,
  },

  // ── 7. Consultation record (9 ข้อ) ──
  {
    id: 'ipd_c7_1',
    rowId: 'ipd_c7',
    criteriaIndex: 0,
    category: '7. Consultation record',
    criteriaNo: 1,
    title: 'วันเดือนปี เวลา ความจำเป็นรีบด่วน และหน่วยงานที่ขอ',
    description: 'มีบันทึกวันเดือนปี เวลา ความจำเป็นรีบด่วน และหน่วยงานที่ขอปรึกษา',
    canBeNA: true,
  },
  {
    id: 'ipd_c7_2',
    rowId: 'ipd_c7',
    criteriaIndex: 1,
    category: '7. Consultation record',
    criteriaNo: 2,
    title: 'ระบุปัญหาที่ต้องการปรึกษาที่ชัดเจน',
    description: 'มีการบันทึกขอปรึกษา โดยระบุปัญหาและวัตถุประสงค์ที่ต้องการปรึกษาอย่างชัดเจน',
    canBeNA: true,
  },
  {
    id: 'ipd_c7_3',
    rowId: 'ipd_c7',
    criteriaIndex: 2,
    category: '7. Consultation record',
    criteriaNo: 3,
    title: 'บันทึกประวัติ ตรวจร่างกาย และการรักษาโดยย่อของผู้ขอ',
    description: 'มีบันทึกประวัติการตรวจร่างกายและการรักษาโดยย่อ ของแพทย์ผู้ขอปรึกษา',
    canBeNA: true,
  },
  {
    id: 'ipd_c7_4',
    rowId: 'ipd_c7',
    criteriaIndex: 3,
    category: '7. Consultation record',
    criteriaNo: 4,
    title: 'ลายมือชื่อแพทย์ผู้ขอปรึกษา และเลขที่ ว.',
    description: 'มีลายมือชื่อแพทย์ผู้ขอปรึกษา ระบุชื่อ สกุล และเลขที่ ว. (ไม่มีลายมือชื่อไม่ได้คะแนนข้อ 1-4)',
    canBeNA: true,
  },
  {
    id: 'ipd_c7_5',
    rowId: 'ipd_c7',
    criteriaIndex: 4,
    category: '7. Consultation record',
    criteriaNo: 5,
    title: 'ผลการตรวจประเมินเพิ่มเติมและคำวินิจฉัยของผู้รับปรึกษา',
    description: 'มีบันทึกผลการตรวจประเมินเพิ่มเติมและคำวินิจฉัยของผู้รับปรึกษา',
    canBeNA: true,
  },
  {
    id: 'ipd_c7_6',
    rowId: 'ipd_c7',
    criteriaIndex: 5,
    category: '7. Consultation record',
    criteriaNo: 6,
    title: 'ความเห็น แผนการรักษา หรือการให้คำแนะนำ',
    description: 'มีบันทึกความเห็น หรือแผนการรักษา หรือคำแนะนำของผู้รับปรึกษา',
    canBeNA: true,
  },
  {
    id: 'ipd_c7_7',
    rowId: 'ipd_c7',
    criteriaIndex: 6,
    category: '7. Consultation record',
    criteriaNo: 7,
    title: 'วันเดือนปีและเวลาที่ผู้รับปรึกษามาตรวจผู้ป่วย',
    description: 'มีบันทึก วัน เดือน ปี และเวลา ที่ผู้รับปรึกษามาตรวจผู้ป่วย',
    canBeNA: true,
  },
  {
    id: 'ipd_c7_8',
    rowId: 'ipd_c7',
    criteriaIndex: 7,
    category: '7. Consultation record',
    criteriaNo: 8,
    title: 'ลายมือชื่อแพทย์ผู้รับปรึกษา และเลขที่ ว.',
    description: 'มีลายมือชื่อแพทย์ผู้ให้คำปรึกษา ระบุชื่อ สกุล และเลขที่ ว. (ไม่มีลายมือชื่อไม่ได้คะแนนข้อ 5-8)',
    canBeNA: true,
  },
  {
    id: 'ipd_c7_9',
    rowId: 'ipd_c7',
    criteriaIndex: 8,
    category: '7. Consultation record',
    criteriaNo: 9,
    title: 'บันทึกผลการให้คำปรึกษาลงตรงตำแหน่งที่กำหนด',
    description: 'แพทย์ผู้รับปรึกษา บันทึกผลการให้คำปรึกษาลงตรงตำแหน่งหรือแบบฟอร์มที่กำหนด',
    canBeNA: true,
  },

  // ── 8. Anesthetic record (9 ข้อ) ──
  {
    id: 'ipd_c8_1',
    rowId: 'ipd_c8',
    criteriaIndex: 0,
    category: '8. Anesthetic record',
    criteriaNo: 1,
    title: 'Status ผู้ป่วยก่อนให้ยาระงับความรู้สึก และวิธีให้',
    description: 'บันทึก status ผู้ป่วยก่อนให้ยาระงับความรู้สึก (ASA physical status) และวิธีระงับความรู้สึก',
    canBeNA: true,
  },
  {
    id: 'ipd_c8_2',
    rowId: 'ipd_c8',
    criteriaIndex: 1,
    category: '8. Anesthetic record',
    criteriaNo: 2,
    title: 'บันทึกโรคก่อนผ่าตัด สอดคล้องกับการวินิจฉัยแพทย์',
    description: 'บันทึกโรคก่อนผ่าตัด ซึ่งต้องสอดคล้องกับการวินิจฉัยของแพทย์ (ขัดแย้งกันถือว่าไม่ผ่าน)',
    canBeNA: true,
  },
  {
    id: 'ipd_c8_3',
    rowId: 'ipd_c8',
    criteriaIndex: 2,
    category: '8. Anesthetic record',
    criteriaNo: 3,
    title: 'บันทึกชนิดและชื่อการผ่าตัด สอดคล้องกับแพทย์ผ่าตัด',
    description: 'บันทึกชนิดและชื่อการผ่าตัด สอดคล้องกับการผ่าตัดของแพทย์ (ขัดแย้งกันถือว่าไม่ผ่าน)',
    canBeNA: true,
  },
  {
    id: 'ipd_c8_4',
    rowId: 'ipd_c8',
    criteriaIndex: 3,
    category: '8. Anesthetic record',
    criteriaNo: 4,
    title: 'Pre-anesthetic evaluation โดยทีมวิสัญญี',
    description: 'มีบันทึกตรวจประเมินก่อนผ่าตัดโดยทีมวิสัญญี และระบุประวัติการระงับความรู้สึกก่อนหน้า (ถ้ามี)',
    canBeNA: true,
  },
  {
    id: 'ipd_c8_5',
    rowId: 'ipd_c8',
    criteriaIndex: 4,
    category: '8. Anesthetic record',
    criteriaNo: 5,
    title: 'บันทึกสัญญาณชีพและเฝ้าระวังระหว่างดมยาทุก 5 นาที',
    description: 'มีบันทึกสัญญาณชีพและการเฝ้าระวังระหว่างดมยาอย่างเหมาะสมทุก 5 นาที',
    canBeNA: true,
  },
  {
    id: 'ipd_c8_6',
    rowId: 'ipd_c8',
    criteriaIndex: 5,
    category: '8. Anesthetic record',
    criteriaNo: 6,
    title: 'บันทึก Intake, Output, Blood loss และผลรวม',
    description: 'มีบันทึก intake, output, blood loss, total intake และ total output ครบถ้วน',
    canBeNA: true,
  },
  {
    id: 'ipd_c8_7',
    rowId: 'ipd_c8',
    criteriaIndex: 6,
    category: '8. Anesthetic record',
    criteriaNo: 7,
    title: 'บันทึกการดูแลใน Recovery room หลังผ่าตัด 1 ชั่วโมง',
    description: 'บันทึกการดูแลหลังผ่าตัด 1 ชม. ใน recovery room ตามมาตรฐานราชวิทยาลัยวิสัญญีแพทย์ (on ET-tube ส่งตึกระบุ NA)',
    canBeNA: true,
  },
  {
    id: 'ipd_c8_8',
    rowId: 'ipd_c8',
    criteriaIndex: 7,
    category: '8. Anesthetic record',
    criteriaNo: 8,
    title: 'Post anesthetic round โดยทีมวิสัญญี',
    description: 'บันทึกการเยี่ยมดูแลหลังผ่าตัดโดยทีมวิสัญญี และระบุปัญหาจากการระงับความรู้สึก (ถ้าไม่มีระบุ "ไม่พบปัญหา")',
    canBeNA: true,
  },
  {
    id: 'ipd_c8_9',
    rowId: 'ipd_c8',
    criteriaIndex: 8,
    category: '8. Anesthetic record',
    criteriaNo: 9,
    title: 'ลายมือชื่อวิสัญญีแพทย์/พยาบาลวิสัญญีผู้รับผิดชอบ',
    description: 'บันทึกด้วยลายมือที่อ่านออกได้และระบุ ชื่อ นามสกุล วิสัญญีแพทย์หรือวิสัญญีพยาบาลที่รับผิดชอบ',
    canBeNA: true,
  },

  // ── 9. Operative note (9 ข้อ) ──
  {
    id: 'ipd_c9_1',
    rowId: 'ipd_c9',
    criteriaIndex: 0,
    category: '9. Operative note',
    criteriaNo: 1,
    title: 'ข้อมูลผู้ป่วยครบถ้วน (ชื่อ สกุล อายุ HN AN เพศ)',
    description: 'มีการบันทึกข้อมูลผู้ป่วยถูกต้อง ครบถ้วน ประกอบด้วย ชื่อ สกุล อายุ HN AN เพศ เป็นต้น',
    canBeNA: true,
  },
  {
    id: 'ipd_c9_2',
    rowId: 'ipd_c9',
    criteriaIndex: 1,
    category: '9. Operative note',
    criteriaNo: 2,
    title: 'บันทึก Pre-op และ Post-op Diagnosis ชัดเจน',
    description: 'บันทึกการวินิจฉัยก่อนและหลังผ่าตัด โดย post-op dx ต้องระบุชื่อโรคที่แพทย์วินิจฉัย ห้ามใช้ same หรือเครื่องหมายปีกกา',
    canBeNA: true,
  },
  {
    id: 'ipd_c9_3',
    rowId: 'ipd_c9',
    criteriaIndex: 2,
    category: '9. Operative note',
    criteriaNo: 3,
    title: 'ชื่อหัตถการถูกต้อง สอดคล้องกับวิธีการทำ',
    description: 'บันทึกชื่อการทำหัตถการ ถูกต้อง ครบถ้วน สอดคล้องกับวิธีการทำหัตถการนั้น',
    canBeNA: true,
  },
  {
    id: 'ipd_c9_4',
    rowId: 'ipd_c9',
    criteriaIndex: 3,
    category: '9. Operative note',
    criteriaNo: 4,
    title: 'รายละเอียด Operative Findings สอดคล้องกับ Post-op Dx',
    description: 'บันทึกรายละเอียดสิ่งที่ตรวจพบ สอดคล้องกับ post-operative diagnosis',
    canBeNA: true,
  },
  {
    id: 'ipd_c9_5',
    rowId: 'ipd_c9',
    criteriaIndex: 4,
    category: '9. Operative note',
    criteriaNo: 5,
    title: 'รายละเอียดวิธีการผ่าตัด (Position, Incision, ชิ้นเนื้อ)',
    description: 'บันทึกรายละเอียดวิธีการทำหัตถการ position, incision, สิ่งที่ตัดออก รวมถึงการส่งชิ้นเนื้อ pathology',
    canBeNA: true,
  },
  {
    id: 'ipd_c9_6',
    rowId: 'ipd_c9',
    criteriaIndex: 5,
    category: '9. Operative note',
    criteriaNo: 6,
    title: 'ภาวะแทรกซ้อนและปริมาณเลือดที่สูญเสีย (Blood loss)',
    description: 'บันทึกภาวะแทรกซ้อนและเลือดที่สูญเสีย (ใช้ minimal blood loss ได้ ถ้าไม่มีระบุ "ไม่มี")',
    canBeNA: true,
  },
  {
    id: 'ipd_c9_7',
    rowId: 'ipd_c9',
    criteriaIndex: 6,
    category: '9. Operative note',
    criteriaNo: 7,
    title: 'วันและเวลาที่เริ่มต้นและสิ้นสุดการผ่าตัด',
    description: 'บันทึกวัน เวลา ที่เริ่มต้นและสิ้นสุดการทำหัตถการอย่างชัดเจน',
    canBeNA: true,
  },
  {
    id: 'ipd_c9_8',
    rowId: 'ipd_c9',
    criteriaIndex: 7,
    category: '9. Operative note',
    criteriaNo: 8,
    title: 'คณะผู้ร่วมทำหัตถการ และวิธีให้ยาระงับความรู้สึก',
    description: 'บันทึก ชื่อ-นามสกุล คณะผู้ร่วมทำหัตถการ (แพทย์, วิสัญญี, scrub nurse) และวิธีระงับความรู้สึก',
    canBeNA: true,
  },
  {
    id: 'ipd_c9_9',
    rowId: 'ipd_c9',
    criteriaIndex: 8,
    category: '9. Operative note',
    criteriaNo: 9,
    title: 'ลายมือชื่อแพทย์ผู้ทำหัตถการ และเลขที่ ว.',
    description: 'บันทึกด้วยลายมือที่อ่านออกได้ และลงลายมือชื่อแพทย์ผู้ทำหัตถการ ระบุชื่อ สกุล และเลขที่ ว. (หรือสืบค้น EMR log in)',
    canBeNA: true,
  },

  // ── 10. Labour record (9 ข้อ) ──
  {
    id: 'ipd_c10_1',
    rowId: 'ipd_c10',
    criteriaIndex: 0,
    category: '10. Labour record',
    criteriaNo: 1,
    title: 'ประเมินผู้คลอดแรกรับ: Obstetric & ANC history, PE',
    description: 'บันทึกประเมินแรกรับ: G, P, A, L, LMP, EDC, GA, ANC history, complication, risk monitoring และ PE',
    canBeNA: true,
  },
  {
    id: 'ipd_c10_2',
    rowId: 'ipd_c10',
    criteriaIndex: 1,
    category: '10. Labour record',
    criteriaNo: 2,
    title: 'ประเมินระยะรอคลอด: V/S, Progress labour, FHS',
    description: 'ประเมินระยะรอคลอด: ว/ด/ป เวลา ชีพจร BP progress labour (contraction, dilation, effacement), fetal assessment',
    canBeNA: true,
  },
  {
    id: 'ipd_c10_3',
    rowId: 'ipd_c10',
    criteriaIndex: 2,
    category: '10. Labour record',
    criteriaNo: 3,
    title: 'บันทึกวันที่ ระยะเวลา การคลอดแต่ละ Stage',
    description: 'บันทึกวันที่ ระยะเวลา การคลอดแต่ละ stage (กรณี elective C/S ระบุ NA)',
    canBeNA: true,
  },
  {
    id: 'ipd_c10_4',
    rowId: 'ipd_c10',
    criteriaIndex: 3,
    category: '10. Labour record',
    criteriaNo: 4,
    title: 'หัตถการ วิธีคลอด ข้อบ่งชี้ และ Episiotomy',
    description: 'บันทึกหัตถการ วิธีการคลอด ข้อบ่งชี้ ภาวะแทรกซ้อน การระงับความรู้สึก และการทำ episiotomy',
    canBeNA: true,
  },
  {
    id: 'ipd_c10_5',
    rowId: 'ipd_c10',
    criteriaIndex: 4,
    category: '10. Labour record',
    criteriaNo: 5,
    title: 'คำสั่งและบันทึกการให้ยาในระยะก่อน ระหว่าง หลังคลอด',
    description: 'มีบันทึกคำสั่ง และบันทึกการให้ยาในระยะก่อน ระหว่าง และหลังคลอด',
    canBeNA: true,
  },
  {
    id: 'ipd_c10_6',
    rowId: 'ipd_c10',
    criteriaIndex: 5,
    category: '10. Labour record',
    criteriaNo: 6,
    title: 'วันเวลาทารกคลอด เพศ น้ำหนัก และความยาว',
    description: 'บันทึก วันเดือนปี และเวลาที่ทารกคลอด เพศ น้ำหนัก และความยาวของทารก',
    canBeNA: true,
  },
  {
    id: 'ipd_c10_7',
    rowId: 'ipd_c10',
    criteriaIndex: 6,
    category: '10. Labour record',
    criteriaNo: 7,
    title: 'ประเมินมารดาหลังคลอด (Placenta, Blood loss, V/S)',
    description: 'ประเมินมารดาหลังคลอด: placenta checked, complication, blood loss, vital signs สภาพก่อนย้าย/หลังคลอด 2 ชม.',
    canBeNA: true,
  },
  {
    id: 'ipd_c10_8',
    rowId: 'ipd_c10',
    criteriaIndex: 7,
    category: '10. Labour record',
    criteriaNo: 8,
    title: 'ประเมินทารก Apgar score (1, 5, 10 นาที) และภาวะแทรกซ้อน',
    description: 'บันทึกประเมินทารก Apgar score 1, 5, 10 นาที initial assessment และประเมินภาวะแทรกซ้อน (ถ้าไม่มีระบุ "ไม่มี")',
    canBeNA: true,
  },
  {
    id: 'ipd_c10_9',
    rowId: 'ipd_c10',
    criteriaIndex: 8,
    category: '10. Labour record',
    criteriaNo: 9,
    title: 'ลายมือชื่อแพทย์หรือพยาบาลผู้ทำคลอด',
    description: 'บันทึกด้วยลายมือที่อ่านออกได้ และลงลายมือชื่อแพทย์ หรือพยาบาลวิชาชีพผู้ทำคลอด ระบุชื่อและนามสกุล',
    canBeNA: true,
  },

  // ── 11. Rehabilitation record (9 ข้อ) ──
  {
    id: 'ipd_c11_1',
    rowId: 'ipd_c11',
    criteriaIndex: 0,
    category: '11. Rehabilitation record',
    criteriaNo: 1,
    title: 'ซักประวัติ CC, PI, Past illness ที่ต้องการฟื้นฟู',
    description: 'บันทึกซักประวัติอาการสำคัญ ประวัติปัจจุบัน และอดีตที่เกี่ยวข้องกับปัญหาที่ต้องการฟื้นฟูสมรรถภาพ',
    canBeNA: true,
  },
  {
    id: 'ipd_c11_2',
    rowId: 'ipd_c11',
    criteriaIndex: 1,
    category: '11. Rehabilitation record',
    criteriaNo: 2,
    title: 'ตรวจร่างกายในส่วนที่เกี่ยวข้องกับการฟื้นฟูสมรรถภาพ',
    description: 'บันทึกการตรวจร่างกายในส่วนที่เกี่ยวข้อง สอดคล้องกับปัญหาที่ต้องการฟื้นฟูสมรรถภาพ',
    canBeNA: true,
  },
  {
    id: 'ipd_c11_3',
    rowId: 'ipd_c11',
    criteriaIndex: 2,
    category: '11. Rehabilitation record',
    criteriaNo: 3,
    title: 'การวินิจฉัยโรค/ทางกายภาพบำบัด และสรุปปัญหา',
    description: 'บันทึกการวินิจฉัยโรคที่สอดคล้อง หรือวินิจฉัยทางกายภาพบำบัด และสรุปปัญหาที่ต้องการฟื้นฟู',
    canBeNA: true,
  },
  {
    id: 'ipd_c11_4',
    rowId: 'ipd_c11',
    criteriaIndex: 3,
    category: '11. Rehabilitation record',
    criteriaNo: 4,
    title: 'เป้าหมาย แผนฟื้นฟู ชนิดการบำบัด ข้อห้ามข้อควรระวัง',
    description: 'บันทึกเป้าหมาย แผนการฟื้นฟู ชนิดของการบำบัดหรือหัตถการ ข้อห้ามและข้อควรระวัง',
    canBeNA: true,
  },
  {
    id: 'ipd_c11_5',
    rowId: 'ipd_c11',
    criteriaIndex: 4,
    category: '11. Rehabilitation record',
    criteriaNo: 5,
    title: 'บันทึกการรักษาแต่ละครั้ง ระบุตำแหน่งและระยะเวลา',
    description: 'บันทึกการรักษาที่ให้แต่ละครั้ง โดยระบุอวัยวะหรือตำแหน่งที่ทำการบำบัดและระยะเวลาที่ใช้',
    canBeNA: true,
  },
  {
    id: 'ipd_c11_6',
    rowId: 'ipd_c11',
    criteriaIndex: 5,
    category: '11. Rehabilitation record',
    criteriaNo: 6,
    title: 'ประเมินผลและความก้าวหน้าตามเป้าหมายที่ตั้งไว้',
    description: 'บันทึกการประเมินผลการให้บริการ และความก้าวหน้าของการฟื้นฟูสมรรถภาพตามเป้าหมายที่ตั้งไว้',
    canBeNA: true,
  },
  {
    id: 'ipd_c11_7',
    rowId: 'ipd_c11',
    criteriaIndex: 6,
    category: '11. Rehabilitation record',
    criteriaNo: 7,
    title: 'สรุปผลการให้บริการฟื้นฟู และแผนจำหน่ายผู้ป่วย',
    description: 'มีบันทึกสรุปผลการให้บริการฟื้นฟูสมรรถภาพ และแผนการจำหน่ายผู้ป่วย',
    canBeNA: true,
  },
  {
    id: 'ipd_c11_8',
    rowId: 'ipd_c11',
    criteriaIndex: 7,
    category: '11. Rehabilitation record',
    criteriaNo: 8,
    title: 'รายละเอียด Home Program หรือคำแนะนำปฏิบัติตัว',
    description: 'บันทึกรายละเอียดการให้ home program หรือคำแนะนำปฏิบัติตัว (patient/family education) หรือแผนดูแลต่อเนื่อง',
    canBeNA: true,
  },
  {
    id: 'ipd_c11_9',
    rowId: 'ipd_c11',
    criteriaIndex: 8,
    category: '11. Rehabilitation record',
    criteriaNo: 9,
    title: 'ลายมือชื่อแพทย์เวชศาสตร์ฟื้นฟู (ว.) หรือนักกายภาพบำบัด',
    description: 'บันทึกด้วยลายมืออ่านออกได้ และลงลายมือชื่อแพทย์เวชศาสตร์ฟื้นฟู (เลข ว.) หรือนักกายภาพบำบัด (ชื่อ สกุล ตำแหน่ง)',
    canBeNA: true,
  },

  // ── 12. Nurses' note (9 ข้อ) ──
  {
    id: 'ipd_c12_1',
    rowId: 'ipd_c12',
    criteriaIndex: 0,
    category: "12. Nurses' note (บันทึกการพยาบาล)",
    criteriaNo: 1,
    title: 'การประเมินแรกรับ: CC ระยะเวลา ประวัติ และเวลาแรกรับ',
    description: 'อาการสำคัญ 1-2 อาการตามด้วยระยะเวลา, ซักประวัติเจ็บป่วยตามลำดับเวลา, อาการแรกรับตามสภาวะ และระบุเวลาแรกรับ',
    canBeNA: false,
  },
  {
    id: 'ipd_c12_2',
    rowId: 'ipd_c12',
    criteriaIndex: 1,
    category: "12. Nurses' note (บันทึกการพยาบาล)",
    criteriaNo: 2,
    title: 'ระบุปัญหาการพยาบาลที่สำคัญสอดคล้องกับอาการแสดง',
    description: 'ระบุปัญหาการพยาบาลที่สำคัญสอดคล้องกับอาการแสดงด้านร่างกาย จิตใจ อารมณ์ สังคม จิตวิญญาณ ตั้งแต่แรกรับจนจำหน่าย',
    canBeNA: false,
  },
  {
    id: 'ipd_c12_3',
    rowId: 'ipd_c12',
    criteriaIndex: 2,
    category: "12. Nurses' note (บันทึกการพยาบาล)",
    criteriaNo: 3,
    title: 'กิจกรรมการพยาบาล และการประเมินซ้ำ (Early detection)',
    description: 'ระบุกิจกรรมการพยาบาลครอบคลุมปัญหา, มีการประเมินซ้ำตามช่วงเวลา (early detection รายงานแพทย์ทันเวลา) และตอบสนองทีมสุขภาพ',
    canBeNA: false,
  },
  {
    id: 'ipd_c12_4',
    rowId: 'ipd_c12',
    criteriaIndex: 3,
    category: "12. Nurses' note (บันทึกการพยาบาล)",
    criteriaNo: 4,
    title: 'ประเมินการตอบสนองต่อการรักษาพยาบาลและการทำหัตถการ',
    description: 'บันทึกการเปลี่ยนแปลงตอบสนองการพยาบาล/การรักษาแพทย์, บันทึกการตรวจ/รักษาสำคัญ (วันเวลา อาการก่อน ขณะ หลังทำ และผล)',
    canBeNA: false,
  },
  {
    id: 'ipd_c12_5',
    rowId: 'ipd_c12',
    criteriaIndex: 4,
    category: "12. Nurses' note (บันทึกการพยาบาล)",
    criteriaNo: 5,
    title: 'การให้ข้อมูลระหว่างการรักษาพยาบาลและช่วยเหลือผู้ป่วย',
    description: 'บันทึกการให้ข้อมูลที่จำเป็นและการช่วยเหลือด้านร่างกาย อารมณ์ จิตใจ และคำปรึกษาสอดคล้องกับปัญหาผู้ป่วย/ครอบครัว',
    canBeNA: false,
  },
  {
    id: 'ipd_c12_6',
    rowId: 'ipd_c12',
    criteriaIndex: 5,
    category: "12. Nurses' note (บันทึกการพยาบาล)",
    criteriaNo: 6,
    title: 'การเตรียมความพร้อมดูแลต่อเนื่องที่บ้าน (Discharge plan)',
    description: 'ระบุอาการ/ปัญหาหลังจำหน่าย, ให้ข้อมูลสอนการดูแลตนเอง, และระบุข้อมูลที่สะท้อนความก้าวหน้าในการเรียนรู้',
    canBeNA: false,
  },
  {
    id: 'ipd_c12_7',
    rowId: 'ipd_c12',
    criteriaIndex: 6,
    category: "12. Nurses' note (บันทึกการพยาบาล)",
    criteriaNo: 7,
    title: 'การประสานการดูแลต่อเนื่องในโรงพยาบาลและชุมชน',
    description: 'ระบุปัญหาความต้องการที่ต้องดูแลต่อเนื่องใน รพ. และชุมชน, บันทึกการนัดหมายและแนวทางช่วยเหลือ/คำปรึกษา',
    canBeNA: false,
  },
  {
    id: 'ipd_c12_8',
    rowId: 'ipd_c12',
    criteriaIndex: 7,
    category: "12. Nurses' note (บันทึกการพยาบาล)",
    criteriaNo: 8,
    title: 'การจำหน่ายผู้ป่วย: สรุปอาการแสดง V/S และคำแนะนำ',
    description: 'สรุปอาการแสดง V/S และความพร้อมก่อนจำหน่าย, กิจกรรมพยาบาลก่อนจำหน่าย (คำแนะนำ/การดูแลต่อเนื่อง/นัดตรวจ) และข้อมูลส่งต่อ',
    canBeNA: false,
  },
  {
    id: 'ipd_c12_9',
    rowId: 'ipd_c12',
    criteriaIndex: 8,
    category: "12. Nurses' note (บันทึกการพยาบาล)",
    criteriaNo: 9,
    title: 'วันเดือนปี เวลา และลงลายมือชื่อพยาบาลผู้บันทึกทุกครั้ง',
    description: 'แรกรับ, ระหว่างดูแล (สัมพันธ์กับการเปลี่ยนแปลง/คำสั่งแพทย์/MAR), ก่อนจำหน่าย, ลงลายมือชื่อและนามสกุลพยาบาลผู้บันทึกทุกครั้ง',
    canBeNA: false,
  },
];
